### ISSUE TITLE
"Add map"

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/MapWalk#37]
I'd like to be able to upload new maps from my iPhone. 

- Add a "+" to the maps list
- when tapped, let user browse iPhone photos for an image (ideally a map, but we don't care for now)
- import the photo into a directory that we can access later (eg. we could create an online directory of maps for everyone)
- ask for the year of the map (allow user to type text like "tbd")
- ask for the location of the photo (any text)
- add this map to the map list with name in format "year-location"
- add the ability to delete maps: press-hold on a map icon brings up "delete?" dialog for that map

**Comment by tedbarnett** [comment]
And can we save the current map data in a text-readable file of some kind?  I am afraid I will spend time setting up some new maps and then lose all the data later when I delete/install MapWalk.

List each map's year, location, file name, path.

**Comment by bhautikpatoliya004** [comment]
> And can we save the current map data in a text-readable file of some kind? I am afraid I will spend time setting up some new maps and then lose all the data later when I delete/install MapWalk.
> 
> List each map's year, location, file name, path, and the GPS location of each of the 4 corners of the image (since we may later enable "stretching" of maps to more precisely align them)

**Do we need to store/save user picked images too as you suggested?** 
If **NO**, then we can simply export/save pre added Maps(Castello - 1660, Holland - 1776 and GreatFire - 1776) data (map's year, location, file name, path, and the GPS location of each of the 4 corners of the image) in the file and export in Files app or any other place. This will not save/include user picked images.

If **YES**, then we need to export/backup in the cloud like Google Driver, iCloud or Dropbox and then we can give an option import those backup data later after installing again. This will save/include user picked images too.

Please let me know your thoughts.
